# Generated by Django 3.1.1 on 2021-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210115_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('PR', 'primary'), ('SC', 'secondary'), ('DR', 'danger')], max_length=2),
        ),
    ]
