# Generated by Django 3.1.1 on 2021-01-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210115_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ST', 'Shirt'), ('SW', 'Sport Wear'), ('OW', 'Out Wear')], max_length=2),
        ),
    ]
